console.log("hi")
const quotes=[
    "The best way to predict your future is to create it." ,
"In the middle of every difficulty lies opportunity." ,
"Life is 10% what happens to us and 90% how we react to it." ,
"The only way to do great work is to love what you do." ,
"Believe you can and you’re halfway there." ,
"Success is not final, failure is not fatal: It is the courage to continue that counts." ,
"Do not go where the path may lead, go instead where there is no path and leave a trail." ,
"Your time is limited, don't waste it living someone else's life." ,
"Change your thoughts and you change your world." ,
"Success usually comes to those who are too busy to be looking for it." ,
"Happiness is not something ready-made. It comes from your own actions." ,
"You miss 100% of the shots you don’t take." ,
"Don’t wait for opportunity. Create it." ,
"The best revenge is massive success." ,
"Strive not to be a success, but rather to be of value." ,
"I am not a product of my circumstances. I am a product of my decisions." ,
"What lies behind us and what lies before us are tiny matters compared to what lies within us." ,
"It’s never too late to be what you might have been." ,
"The only limit to our realization of tomorrow is our doubts of today." ,
"If you want to fly, you have to give up the things that weigh you down." ,
"Go confidently in the direction of your dreams. Live the life you have imagined." ,
"Success is not the key to happiness. Happiness is the key to success." ,
"Don’t count the days, make the days count." ,
"Everything you’ve ever wanted is on the other side of fear." ,
"It is never too late to be what you might have been." ,
"If you’re going through hell, keep going." ,
"Life isn’t about finding yourself. Life is about creating yourself." ,
"You have power over your mind, not outside events. Realize this, and you will find strength." ,
"The journey of a thousand miles begins with one step." ,
"The only impossible journey is the one you never begin." ,
"The best way to escape from your problems is to solve them." ,
"To live is the rarest thing in the world. Most people exist, that is all." ,
"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
"The only person you are destined to become is the person you decide to be." ,
"It always seems impossible until it’s done." ,
"Doubt kills more dreams than failure ever will." ,
"What you get by achieving your goals is not as important as what you become by achieving your goals." ,
"The only thing standing between you and your goal is the story you keep telling yourself." ,
"Act as if what you do makes a difference. It does." ,
"Keep your face always toward the sunshine, and shadows will fall behind you." ,
"Success is the sum of small efforts, repeated day-in and day-out." ,
"You are never too old to set another goal or to dream a new dream." ,
"Don’t be pushed by your problems, be led by your dreams." ,
"What we achieve inwardly will change outer reality." ,
"The future depends on what you do today." ,
"Don’t watch the clock; do what it does. Keep going." ,
"I can’t change the direction of the wind, but I can adjust my sails to always reach my destination." ,
"Success is liking yourself, liking what you do, and liking how you do it." ,
"Start where you are. Use what you have. Do what you can." ,
"Success doesn’t come from what you do occasionally. It comes from what you do consistently." ,
"The only way to achieve the impossible is to believe it is possible." ,
"Your life does not get better by chance, it gets better by change." ,
"You don’t have to be great to start, but you have to start to be great." ,
"Small daily improvements over time lead to stunning results." ,
"It’s not about how hard you hit. It’s about how hard you can get hit and keep moving forward." ,
"If opportunity doesn’t knock, build a door." ,
"The only limits in life are the ones you make." ,
"Dream big and dare to fail." ,
"Life is either a daring adventure or nothing at all." ,
"Do what you can with all you have, wherever you are." ,
"A winner is a dreamer who never gives up." ,
"If you change the way you look at things, the things you look at change." ,
"Don't let the fear of losing be greater than the excitement of winning.", 
"Fall seven times, stand up eight." ,
"Your dreams don’t have an expiration date. Take a deep breath and try again.",
"Courage is resistance to fear, mastery of fear—not absence of fear." ,
"You can't go back and change the beginning, but you can start where you are and change the ending." ,
"The greatest glory in living lies not in never falling, but in rising every time we fall." ,
"Opportunities don't happen. You create them." ,
"What you focus on expands, so focus on what you want." ,
"Failure is not the opposite of success; it’s part of success." ,
"Great things never came from comfort zones." ,
"You will never always be motivated, so you must learn to be disciplined." ,
"Don’t wish it were easier. Wish you were better." ,
"You can’t build a reputation on what you are going to do.",
"The key to success is to start before you are ready.",
"Everything you can imagine is real." ,
"A goal without a plan is just a wish." ,
"Your passion is waiting for your courage to catch up." ,
"Keep going. Everything you need will come to you at the perfect time.",
"Success is walking from failure to failure with no loss of enthusiasm." ,
"You don’t need to see the whole staircase, just take the first step." ,
"Don’t be afraid to give up the good to go for the great." ,
"You can do anything, but not everything." ,
"Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle." ,
"The most effective way to do it, is to do it." ,
"Don’t let yesterday take up too much of today." ,
"The best dreams happen when you’re awake." ,
"It’s not whether you get knocked down, it’s whether you get up." ,
"Success is the progressive realization of a worthy goal or ideal.",
"Do one thing every day that scares you." ,
"Energy and persistence conquer all things." ,
"The secret of getting ahead is getting started." ,
"Hustle beats talent when talent doesn’t hustle." ,
]

const usedIndexes = new Set();

function generateQuote() {
    const quoteElement = document.getElementById("quote"); // Move this inside function for safety
    if (usedIndexes.size === quotes.length) {
        usedIndexes.clear(); // Reset if all quotes have been used
    }

    while (true) {
        const randomIdx = Math.floor(Math.random() * quotes.length);
        if (usedIndexes.has(randomIdx)) continue; // Avoid repeating quotes
        const quote = quotes[randomIdx];
        quoteElement.innerHTML = quote; // Display the new quote
        usedIndexes.add(randomIdx); // Mark this quote as used
        break;
    }
}